export const orgData = [
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
   {
      name: 'name',
      admin: 'admin',
      status: 'status',
      type: 'type',
      date: 'May 1, 2023',
   },
]

export const tableHeaders = [
   'Org name', 'Org admin', 'Status', 'Subscription type', 'Join date'
]